"""fix user id to integer

Revision ID: 0793e1c94dd5
Revises: e8b9b4d8a5b1
Create Date: 2025-08-02 13:56:30.370518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0793e1c94dd5'
down_revision = 'e8b9b4d8a5b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###