// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from './client';
import type { AuthJwtLoginAuthJwtLoginPostData, AuthJwtLoginAuthJwtLoginPostResponses, AuthJwtLoginAuthJwtLoginPostErrors, AuthJwtLogoutAuthJwtLogoutPostData, AuthJwtLogoutAuthJwtLogoutPostResponses, AuthJwtLogoutAuthJwtLogoutPostErrors, RegisterRegisterAuthRegisterPostData, RegisterRegisterAuthRegisterPostResponses, RegisterRegisterAuthRegisterPostErrors, ResetForgotPasswordAuthForgotPasswordPostData, ResetForgotPasswordAuthForgotPasswordPostResponses, ResetForgotPasswordAuthForgotPasswordPostErrors, ResetResetPasswordAuthResetPasswordPostData, ResetResetPasswordAuthResetPasswordPostResponses, ResetResetPasswordAuthResetPasswordPostErrors, VerifyRequestTokenAuthRequestVerifyTokenPostData, VerifyRequestTokenAuthRequestVerifyTokenPostResponses, VerifyRequestTokenAuthRequestVerifyTokenPostErrors, VerifyVerifyAuthVerifyPostData, VerifyVerifyAuthVerifyPostResponses, VerifyVerifyAuthVerifyPostErrors, UsersCurrentUserUsersMeGetData, UsersCurrentUserUsersMeGetResponses, UsersCurrentUserUsersMeGetErrors, UsersPatchCurrentUserUsersMePatchData, UsersPatchCurrentUserUsersMePatchResponses, UsersPatchCurrentUserUsersMePatchErrors, UsersDeleteUserUsersIdDeleteData, UsersDeleteUserUsersIdDeleteResponses, UsersDeleteUserUsersIdDeleteErrors, UsersUserUsersIdGetData, UsersUserUsersIdGetResponses, UsersUserUsersIdGetErrors, UsersPatchUserUsersIdPatchData, UsersPatchUserUsersIdPatchResponses, UsersPatchUserUsersIdPatchErrors, ReadHeroesHeroesGetData, ReadHeroesHeroesGetResponses, ReadHeroesHeroesGetErrors, CreateHeroHeroesPostData, CreateHeroHeroesPostResponses, CreateHeroHeroesPostErrors, DeleteHeroHeroesHeroIdDeleteData, DeleteHeroHeroesHeroIdDeleteResponses, DeleteHeroHeroesHeroIdDeleteErrors, ReadHeroHeroesHeroIdGetData, ReadHeroHeroesHeroIdGetResponses, ReadHeroHeroesHeroIdGetErrors, UpdateHeroHeroesHeroIdPatchData, UpdateHeroHeroesHeroIdPatchResponses, UpdateHeroHeroesHeroIdPatchErrors, ReadRootGetData, ReadRootGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLoginAuthJwtLoginPost = <ThrowOnError extends boolean = false>(options: Options<AuthJwtLoginAuthJwtLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthJwtLoginAuthJwtLoginPostResponses, AuthJwtLoginAuthJwtLoginPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        responseType: 'json',
        url: '/auth/jwt/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogoutAuthJwtLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<AuthJwtLogoutAuthJwtLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AuthJwtLogoutAuthJwtLogoutPostResponses, AuthJwtLogoutAuthJwtLogoutPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/jwt/logout',
        ...options
    });
};

/**
 * Register:Register
 */
export const registerRegisterAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterRegisterAuthRegisterPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterRegisterAuthRegisterPostResponses, RegisterRegisterAuthRegisterPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPasswordAuthForgotPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ResetForgotPasswordAuthForgotPasswordPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResetForgotPasswordAuthForgotPasswordPostResponses, ResetForgotPasswordAuthForgotPasswordPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/auth/forgot-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Reset:Reset Password
 */
export const resetResetPasswordAuthResetPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ResetResetPasswordAuthResetPasswordPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResetResetPasswordAuthResetPasswordPostResponses, ResetResetPasswordAuthResetPasswordPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/auth/reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestTokenAuthRequestVerifyTokenPost = <ThrowOnError extends boolean = false>(options: Options<VerifyRequestTokenAuthRequestVerifyTokenPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VerifyRequestTokenAuthRequestVerifyTokenPostResponses, VerifyRequestTokenAuthRequestVerifyTokenPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/auth/request-verify-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Verify:Verify
 */
export const verifyVerifyAuthVerifyPost = <ThrowOnError extends boolean = false>(options: Options<VerifyVerifyAuthVerifyPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VerifyVerifyAuthVerifyPostResponses, VerifyVerifyAuthVerifyPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/auth/verify',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Users:Current User
 */
export const usersCurrentUserUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<UsersCurrentUserUsersMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UsersCurrentUserUsersMeGetResponses, UsersCurrentUserUsersMeGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserUsersMePatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserUsersMePatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UsersPatchCurrentUserUsersMePatchResponses, UsersPatchCurrentUserUsersMePatchErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Users:Delete User
 */
export const usersDeleteUserUsersIdDelete = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserUsersIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UsersDeleteUserUsersIdDeleteResponses, UsersDeleteUserUsersIdDeleteErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Users:User
 */
export const usersUserUsersIdGet = <ThrowOnError extends boolean = false>(options: Options<UsersUserUsersIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UsersUserUsersIdGetResponses, UsersUserUsersIdGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Users:Patch User
 */
export const usersPatchUserUsersIdPatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserUsersIdPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UsersPatchUserUsersIdPatchResponses, UsersPatchUserUsersIdPatchErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Read Heroes
 */
export const readHeroesHeroesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadHeroesHeroesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReadHeroesHeroesGetResponses, ReadHeroesHeroesGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/heroes/',
        ...options
    });
};

/**
 * Create Hero
 */
export const createHeroHeroesPost = <ThrowOnError extends boolean = false>(options: Options<CreateHeroHeroesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateHeroHeroesPostResponses, CreateHeroHeroesPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/heroes/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Hero
 */
export const deleteHeroHeroesHeroIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteHeroHeroesHeroIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteHeroHeroesHeroIdDeleteResponses, DeleteHeroHeroesHeroIdDeleteErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/heroes/{hero_id}',
        ...options
    });
};

/**
 * Read Hero
 */
export const readHeroHeroesHeroIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadHeroHeroesHeroIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadHeroHeroesHeroIdGetResponses, ReadHeroHeroesHeroIdGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/heroes/{hero_id}',
        ...options
    });
};

/**
 * Update Hero
 */
export const updateHeroHeroesHeroIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateHeroHeroesHeroIdPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateHeroHeroesHeroIdPatchResponses, UpdateHeroHeroesHeroIdPatchErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/heroes/{hero_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReadRootGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};